resolver 127.0.0.11 ipv6=off valid=10s;

map $http_x_canary_release $authoritative_target {
    default                 authoritative:8080;
    "~*^(1|true|canary)$"   authoritative-canary:8080;
}

server {
    listen 8080;
    server_name _;

    location / {
        proxy_pass http://$authoritative_target;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Canary-Router "authoritative-router" always;
        add_header X-Canary-Target $authoritative_target always;
    }
}
