/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StatusEffect = IDL.Record({
  'name' : IDL.Text,
  'effectId' : IDL.Vec(IDL.Nat8),
  'isBuff' : IDL.Bool,
  'description' : IDL.Text,
  'durationSeconds' : IDL.Float64,
  'magnitude' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MobType = IDL.Variant({
  'orc' : IDL.Null,
  'troll' : IDL.Null,
  'custom' : IDL.Text,
  'goblin' : IDL.Null,
  'wraith' : IDL.Null,
  'skeleton' : IDL.Null,
});
export const Position = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const Movement = IDL.Record({
  'canJump' : IDL.Bool,
  'aggroRadius' : IDL.Float64,
  'speed' : IDL.Float64,
  'canFly' : IDL.Bool,
});
export const InventorySystem = IDL.Record({
  'currentInventory' : IDL.Nat,
  'inventoryCapacity' : IDL.Nat,
});
export const Interaction = IDL.Record({
  'interactionType' : IDL.Text,
  'canInteract' : IDL.Bool,
  'interactionRange' : IDL.Float64,
});
export const Navigation = IDL.Record({
  'waypoints' : IDL.Vec(Position),
  'canNavigate' : IDL.Bool,
  'patrolPaths' : IDL.Vec(Position),
});
export const CombatSystem = IDL.Record({
  'damage' : IDL.Int,
  'armor' : IDL.Int,
  'canAttack' : IDL.Bool,
  'weaponType' : IDL.Text,
  'experience' : IDL.Nat,
});
export const StealthSystem = IDL.Record({ 'isHidden' : IDL.Bool });
export const Health = IDL.Record({ 'max' : IDL.Int, 'current' : IDL.Int });
export const Behavior = IDL.Record({
  'movement' : Movement,
  'inventorySystem' : InventorySystem,
  'interaction' : Interaction,
  'navigation' : Navigation,
  'combatSystem' : CombatSystem,
  'stealthSystem' : StealthSystem,
  'health' : Health,
});
export const Animation = IDL.Record({
  'run' : IDL.Text,
  'hasIdle' : IDL.Bool,
  'hasWalk' : IDL.Bool,
  'hasAttack' : IDL.Bool,
  'idle' : IDL.Text,
  'walk' : IDL.Text,
  'emote' : IDL.Text,
  'hasRun' : IDL.Bool,
  'attack' : IDL.Text,
  'hasEmote' : IDL.Bool,
});
export const Color = IDL.Record({
  'b' : IDL.Float64,
  'g' : IDL.Float64,
  'r' : IDL.Float64,
});
export const Stats = IDL.Record({
  'stamina' : IDL.Int,
  'strength' : IDL.Int,
  'defense' : IDL.Int,
  'agility' : IDL.Int,
  'charisma' : IDL.Int,
  'intelligence' : IDL.Int,
});
export const Appearance = IDL.Record({
  'pattern' : IDL.Text,
  'color' : Color,
  'outfitColor' : Color,
  'stats' : Stats,
  'skinTone' : IDL.Text,
  'material' : IDL.Text,
});
export const MobEntity = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'dangerRating' : IDL.Nat,
  'behavior' : Behavior,
  'activeDebuffs' : IDL.Vec(StatusEffect),
  'activeBuffs' : IDL.Vec(StatusEffect),
  'owner' : IDL.Principal,
  'appearance' : Appearance,
  'name' : IDL.Text,
  'animation' : Animation,
  'mobType' : MobType,
  'position' : Position,
  'health' : Health,
});
export const WeaponObjectType = IDL.Variant({
  'axe' : IDL.Null,
  'bow' : IDL.Null,
  'dagger' : IDL.Null,
  'shield' : IDL.Null,
  'custom' : IDL.Text,
  'mace' : IDL.Null,
  'wand' : IDL.Null,
  'spear' : IDL.Null,
  'staff' : IDL.Null,
  'sword' : IDL.Null,
});
export const CharacterMasteryProgress = IDL.Record({
  'masteryPoints' : IDL.Nat,
  'owner' : IDL.Principal,
  'masteryLevel' : IDL.Nat,
  'unlockedSkillIds' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  'characterId' : IDL.Vec(IDL.Nat8),
  'objectType' : WeaponObjectType,
});
export const NoiseSettings = IDL.Record({
  'roughness' : IDL.Float64,
  'radialWeight' : IDL.Float64,
  'scale' : IDL.Float64,
  'heightRange' : IDL.Float64,
  'noiseSeed' : IDL.Nat,
  'intensity' : IDL.Float64,
});
export const LightingSettings = IDL.Record({
  'sunlight' : IDL.Float64,
  'shadowDepth' : IDL.Float64,
  'directionalIntensity' : IDL.Float64,
  'elevationTransform' : IDL.Float64,
  'ambientLight' : IDL.Float64,
  'intensity' : IDL.Float64,
});
export const BiomeFactors = IDL.Record({
  'biomeType' : IDL.Text,
  'forestDensity' : IDL.Float64,
  'vegetation' : IDL.Float64,
  'soilQuality' : IDL.Float64,
});
export const WindSettings = IDL.Record({
  'direction' : IDL.Float64,
  'iterations' : IDL.Nat,
  'erosionRate' : IDL.Float64,
  'sedimentTransfer' : IDL.Float64,
  'windStrength' : IDL.Float64,
});
export const HydraulicSettings = IDL.Record({
  'waterVolume' : IDL.Float64,
  'depositionRate' : IDL.Float64,
  'evaporationRate' : IDL.Float64,
  'transferRate' : IDL.Float64,
  'sedimentCap' : IDL.Float64,
  'iterations' : IDL.Nat,
  'erosionStr' : IDL.Float64,
  'rainFreq' : IDL.Float64,
  'rainAmount' : IDL.Float64,
  'soilTransfer' : IDL.Float64,
});
export const MountainSettings = IDL.Record({
  'flatteningStr' : IDL.Float64,
  'threshold' : IDL.Float64,
  'plateauHeight' : IDL.Float64,
  'smoothingStr' : IDL.Float64,
  'snowLine' : IDL.Float64,
  'snowCoverage' : IDL.Float64,
});
export const ThermalSettings = IDL.Record({
  'threshold' : IDL.Float64,
  'transferRatio' : IDL.Float64,
  'gravityStrength' : IDL.Float64,
  'creepFactor' : IDL.Float64,
  'incubation' : IDL.Float64,
});
export const RiverSettings = IDL.Record({
  'channelStr' : IDL.Float64,
  'rainfallAmt' : IDL.Float64,
  'evaporation' : IDL.Float64,
  'flowMultiplier' : IDL.Float64,
  'maxRiverLength' : IDL.Nat,
  'tributaryDensity' : IDL.Float64,
  'flowThreshold' : IDL.Float64,
  'springFreq' : IDL.Float64,
  'lakeDepth' : IDL.Float64,
  'riverWidth' : IDL.Float64,
});
export const ErosionSettings = IDL.Record({
  'biomeFactors' : BiomeFactors,
  'wind' : WindSettings,
  'hydraulic' : HydraulicSettings,
  'mountain' : MountainSettings,
  'thermal' : ThermalSettings,
  'river' : RiverSettings,
});
export const CellConfig = IDL.Record({
  'noiseSettings' : NoiseSettings,
  'lightingSettings' : LightingSettings,
  'erosionSettings' : ErosionSettings,
});
export const GridConfig = IDL.Record({
  'dim' : IDL.Nat,
  'owner' : IDL.Principal,
  'cells' : IDL.Vec(IDL.Vec(CellConfig)),
});
export const ItemInstanceMastery = IDL.Record({
  'masteryPoints' : IDL.Nat,
  'owner' : IDL.Principal,
  'masteryLevel' : IDL.Nat,
  'itemInstanceId' : IDL.Vec(IDL.Nat8),
  'characterId' : IDL.Vec(IDL.Nat8),
  'objectType' : WeaponObjectType,
});
export const StatBuffs = IDL.Record({
  'manaBonus' : IDL.Int,
  'agilityBonus' : IDL.Int,
  'strengthBonus' : IDL.Int,
  'healthBonus' : IDL.Int,
});
export const WorldBreakingPowers = IDL.Record({
  'efficientMana' : IDL.Bool,
  'allySummoning' : IDL.Bool,
  'aoeUltimates' : IDL.Bool,
  'reducedCooldowns' : IDL.Bool,
});
export const TierLevel = IDL.Variant({
  'epic' : IDL.Null,
  'legendary' : IDL.Null,
  'rare' : IDL.Null,
  'common' : IDL.Null,
});
export const Resistances = IDL.Record({
  'physicalResistance' : IDL.Float64,
  'poisonResistance' : IDL.Float64,
  'iceResistance' : IDL.Float64,
  'lightningResistance' : IDL.Float64,
  'fireResistance' : IDL.Float64,
});
export const LootItem = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'statBuffs' : IDL.Opt(StatBuffs),
  'debuffAbilities' : IDL.Opt(IDL.Vec(IDL.Text)),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'worldBreakingPowers' : IDL.Opt(WorldBreakingPowers),
  'tier' : TierLevel,
  'defensePower' : IDL.Int,
  'attackPower' : IDL.Int,
  'specialTraits' : IDL.Vec(IDL.Text),
  'resistances' : IDL.Opt(Resistances),
  'elementalPower' : IDL.Int,
  'isExcellent' : IDL.Bool,
});
export const StatRanges = IDL.Record({
  'maxDefense' : IDL.Int,
  'maxAttack' : IDL.Int,
  'minAttack' : IDL.Int,
  'maxElemental' : IDL.Int,
  'minDefense' : IDL.Int,
  'minElemental' : IDL.Int,
});
export const TierDefinition = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'rarityPercentage' : IDL.Float64,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'statRanges' : StatRanges,
  'level' : TierLevel,
  'specialAttributes' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileType = IDL.Variant({
  'FBX' : IDL.Null,
  'GLB' : IDL.Null,
  'OBJ' : IDL.Null,
  'GLTF' : IDL.Null,
});
export const ArchiveType = IDL.Variant({ 'tar' : IDL.Null, 'zip' : IDL.Null });
export const FileMetadata = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'extractionSource' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'owner' : IDL.Principal,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'fileType' : FileType,
  'uploadTimestamp' : IDL.Int,
  'relativePath' : IDL.Text,
  'archiveType' : IDL.Opt(ArchiveType),
  'isDirectory' : IDL.Bool,
});
export const Heightmap = IDL.Record({
  'dim' : IDL.Nat,
  'externalBlob' : ExternalBlob,
  'owner' : IDL.Principal,
});
export const MasterySkill = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'requiredMasteryLevel' : IDL.Nat,
  'objectType' : WeaponObjectType,
});
export const MasteryTree = IDL.Record({
  'owner' : IDL.Principal,
  'objectType' : WeaponObjectType,
  'skills' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const ObjectType = IDL.Variant({
  'interactiveObject' : IDL.Null,
  'playerCharacter' : IDL.Null,
  'environmentalObject' : IDL.Null,
  'collectible' : IDL.Null,
  'vehicle' : IDL.Null,
  'nonPlayerCharacter' : IDL.Null,
  'weapon' : IDL.Null,
});
export const GameObject = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'behavior' : Behavior,
  'owner' : IDL.Principal,
  'appearance' : Appearance,
  'animation' : Animation,
  'position' : Position,
  'objectType' : ObjectType,
});
export const MasteryRollResult = IDL.Record({
  'skillsUnlocked' : IDL.Nat,
  'total' : IDL.Nat,
  'roll1' : IDL.Nat,
  'roll2' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'applyBuffToMob' : IDL.Func([IDL.Vec(IDL.Nat8), StatusEffect], [], []),
  'applyDebuffToMob' : IDL.Func([IDL.Vec(IDL.Nat8), StatusEffect], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllLootItems' : IDL.Func([], [], []),
  'clearMobBuffs' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'clearMobDebuffs' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'createDefaultMobEntity' : IDL.Func(
      [
        IDL.Vec(IDL.Nat8),
        MobType,
        IDL.Text,
        Position,
        Behavior,
        Animation,
        Appearance,
      ],
      [MobEntity],
      [],
    ),
  'deleteFile' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'deleteLootItem' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'deleteMasterySkill' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'deleteMobEntity' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'deleteObjectPrefab' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'deleteTierDefinition' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'getAllCharacterMasteryProgress' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Vec(CharacterMasteryProgress)],
      ['query'],
    ),
  'getAllGridConfigs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat8), GridConfig))],
      ['query'],
    ),
  'getAllItemInstanceMasteries' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Vec(ItemInstanceMastery)],
      ['query'],
    ),
  'getAllLootItems' : IDL.Func([], [IDL.Vec(LootItem)], ['query']),
  'getAllMobEntities' : IDL.Func([], [IDL.Vec(MobEntity)], ['query']),
  'getAllTierDefinitions' : IDL.Func([], [IDL.Vec(TierDefinition)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterMasteryProgress' : IDL.Func(
      [IDL.Vec(IDL.Nat8), WeaponObjectType],
      [IDL.Opt(CharacterMasteryProgress)],
      ['query'],
    ),
  'getDirectoryContents' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'getFile' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Opt(FileMetadata)], ['query']),
  'getFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getFilesByExtractionSource' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'getGridConfig' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(GridConfig)],
      ['query'],
    ),
  'getHeightmap' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(Heightmap)],
      ['query'],
    ),
  'getItemInstanceMastery' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
      [IDL.Opt(ItemInstanceMastery)],
      ['query'],
    ),
  'getLootItem' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Opt(LootItem)], ['query']),
  'getLootItemsByTier' : IDL.Func([TierLevel], [IDL.Vec(LootItem)], ['query']),
  'getLootItemsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(LootItem)],
      ['query'],
    ),
  'getLootTableStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'commonCount' : IDL.Nat,
          'rareCount' : IDL.Nat,
          'legendaryCount' : IDL.Nat,
          'excellentCount' : IDL.Nat,
          'epicCount' : IDL.Nat,
          'totalItems' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMasterySkill' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(MasterySkill)],
      ['query'],
    ),
  'getMasterySkillsByObjectType' : IDL.Func(
      [WeaponObjectType],
      [IDL.Vec(MasterySkill)],
      ['query'],
    ),
  'getMasteryTree' : IDL.Func(
      [WeaponObjectType],
      [IDL.Opt(MasteryTree)],
      ['query'],
    ),
  'getMobBuffDebuffState' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [
        IDL.Opt(
          IDL.Record({
            'dangerRating' : IDL.Nat,
            'activeDebuffs' : IDL.Vec(StatusEffect),
            'activeBuffs' : IDL.Vec(StatusEffect),
          })
        ),
      ],
      ['query'],
    ),
  'getMobEntitiesByDangerRating' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MobEntity)],
      ['query'],
    ),
  'getMobEntity' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(MobEntity)],
      ['query'],
    ),
  'getObjectPrefab' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(GameObject)],
      ['query'],
    ),
  'getObjectPrefabs' : IDL.Func([], [IDL.Vec(GameObject)], ['query']),
  'getTierDefinition' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(TierDefinition)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rollMasteryAdvancement' : IDL.Func(
      [IDL.Vec(IDL.Nat8), WeaponObjectType, IDL.Nat],
      [MasteryRollResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCharacterMasteryProgress' : IDL.Func([CharacterMasteryProgress], [], []),
  'saveFile' : IDL.Func(
      [
        IDL.Vec(IDL.Nat8),
        ExternalBlob,
        IDL.Text,
        IDL.Nat,
        FileType,
        IDL.Int,
        IDL.Opt(IDL.Vec(IDL.Nat8)),
        IDL.Text,
        IDL.Bool,
        IDL.Opt(ArchiveType),
      ],
      [],
      [],
    ),
  'saveGridConfig' : IDL.Func([IDL.Vec(IDL.Nat8), GridConfig], [], []),
  'saveHeightmap' : IDL.Func(
      [IDL.Vec(IDL.Nat8), ExternalBlob, IDL.Nat],
      [],
      [],
    ),
  'saveItemInstanceMastery' : IDL.Func([ItemInstanceMastery], [], []),
  'saveLootItem' : IDL.Func([IDL.Vec(IDL.Nat8), LootItem], [], []),
  'saveLootItemBatch' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat8), LootItem))],
      [],
      [],
    ),
  'saveMasterySkill' : IDL.Func([IDL.Vec(IDL.Nat8), MasterySkill], [], []),
  'saveMasteryTree' : IDL.Func(
      [WeaponObjectType, IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  'saveMobEntity' : IDL.Func([IDL.Vec(IDL.Nat8), MobEntity], [], []),
  'saveObjectPrefab' : IDL.Func([IDL.Vec(IDL.Nat8), GameObject], [], []),
  'saveTierDefinition' : IDL.Func([IDL.Vec(IDL.Nat8), TierDefinition], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StatusEffect = IDL.Record({
    'name' : IDL.Text,
    'effectId' : IDL.Vec(IDL.Nat8),
    'isBuff' : IDL.Bool,
    'description' : IDL.Text,
    'durationSeconds' : IDL.Float64,
    'magnitude' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MobType = IDL.Variant({
    'orc' : IDL.Null,
    'troll' : IDL.Null,
    'custom' : IDL.Text,
    'goblin' : IDL.Null,
    'wraith' : IDL.Null,
    'skeleton' : IDL.Null,
  });
  const Position = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const Movement = IDL.Record({
    'canJump' : IDL.Bool,
    'aggroRadius' : IDL.Float64,
    'speed' : IDL.Float64,
    'canFly' : IDL.Bool,
  });
  const InventorySystem = IDL.Record({
    'currentInventory' : IDL.Nat,
    'inventoryCapacity' : IDL.Nat,
  });
  const Interaction = IDL.Record({
    'interactionType' : IDL.Text,
    'canInteract' : IDL.Bool,
    'interactionRange' : IDL.Float64,
  });
  const Navigation = IDL.Record({
    'waypoints' : IDL.Vec(Position),
    'canNavigate' : IDL.Bool,
    'patrolPaths' : IDL.Vec(Position),
  });
  const CombatSystem = IDL.Record({
    'damage' : IDL.Int,
    'armor' : IDL.Int,
    'canAttack' : IDL.Bool,
    'weaponType' : IDL.Text,
    'experience' : IDL.Nat,
  });
  const StealthSystem = IDL.Record({ 'isHidden' : IDL.Bool });
  const Health = IDL.Record({ 'max' : IDL.Int, 'current' : IDL.Int });
  const Behavior = IDL.Record({
    'movement' : Movement,
    'inventorySystem' : InventorySystem,
    'interaction' : Interaction,
    'navigation' : Navigation,
    'combatSystem' : CombatSystem,
    'stealthSystem' : StealthSystem,
    'health' : Health,
  });
  const Animation = IDL.Record({
    'run' : IDL.Text,
    'hasIdle' : IDL.Bool,
    'hasWalk' : IDL.Bool,
    'hasAttack' : IDL.Bool,
    'idle' : IDL.Text,
    'walk' : IDL.Text,
    'emote' : IDL.Text,
    'hasRun' : IDL.Bool,
    'attack' : IDL.Text,
    'hasEmote' : IDL.Bool,
  });
  const Color = IDL.Record({
    'b' : IDL.Float64,
    'g' : IDL.Float64,
    'r' : IDL.Float64,
  });
  const Stats = IDL.Record({
    'stamina' : IDL.Int,
    'strength' : IDL.Int,
    'defense' : IDL.Int,
    'agility' : IDL.Int,
    'charisma' : IDL.Int,
    'intelligence' : IDL.Int,
  });
  const Appearance = IDL.Record({
    'pattern' : IDL.Text,
    'color' : Color,
    'outfitColor' : Color,
    'stats' : Stats,
    'skinTone' : IDL.Text,
    'material' : IDL.Text,
  });
  const MobEntity = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'dangerRating' : IDL.Nat,
    'behavior' : Behavior,
    'activeDebuffs' : IDL.Vec(StatusEffect),
    'activeBuffs' : IDL.Vec(StatusEffect),
    'owner' : IDL.Principal,
    'appearance' : Appearance,
    'name' : IDL.Text,
    'animation' : Animation,
    'mobType' : MobType,
    'position' : Position,
    'health' : Health,
  });
  const WeaponObjectType = IDL.Variant({
    'axe' : IDL.Null,
    'bow' : IDL.Null,
    'dagger' : IDL.Null,
    'shield' : IDL.Null,
    'custom' : IDL.Text,
    'mace' : IDL.Null,
    'wand' : IDL.Null,
    'spear' : IDL.Null,
    'staff' : IDL.Null,
    'sword' : IDL.Null,
  });
  const CharacterMasteryProgress = IDL.Record({
    'masteryPoints' : IDL.Nat,
    'owner' : IDL.Principal,
    'masteryLevel' : IDL.Nat,
    'unlockedSkillIds' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'characterId' : IDL.Vec(IDL.Nat8),
    'objectType' : WeaponObjectType,
  });
  const NoiseSettings = IDL.Record({
    'roughness' : IDL.Float64,
    'radialWeight' : IDL.Float64,
    'scale' : IDL.Float64,
    'heightRange' : IDL.Float64,
    'noiseSeed' : IDL.Nat,
    'intensity' : IDL.Float64,
  });
  const LightingSettings = IDL.Record({
    'sunlight' : IDL.Float64,
    'shadowDepth' : IDL.Float64,
    'directionalIntensity' : IDL.Float64,
    'elevationTransform' : IDL.Float64,
    'ambientLight' : IDL.Float64,
    'intensity' : IDL.Float64,
  });
  const BiomeFactors = IDL.Record({
    'biomeType' : IDL.Text,
    'forestDensity' : IDL.Float64,
    'vegetation' : IDL.Float64,
    'soilQuality' : IDL.Float64,
  });
  const WindSettings = IDL.Record({
    'direction' : IDL.Float64,
    'iterations' : IDL.Nat,
    'erosionRate' : IDL.Float64,
    'sedimentTransfer' : IDL.Float64,
    'windStrength' : IDL.Float64,
  });
  const HydraulicSettings = IDL.Record({
    'waterVolume' : IDL.Float64,
    'depositionRate' : IDL.Float64,
    'evaporationRate' : IDL.Float64,
    'transferRate' : IDL.Float64,
    'sedimentCap' : IDL.Float64,
    'iterations' : IDL.Nat,
    'erosionStr' : IDL.Float64,
    'rainFreq' : IDL.Float64,
    'rainAmount' : IDL.Float64,
    'soilTransfer' : IDL.Float64,
  });
  const MountainSettings = IDL.Record({
    'flatteningStr' : IDL.Float64,
    'threshold' : IDL.Float64,
    'plateauHeight' : IDL.Float64,
    'smoothingStr' : IDL.Float64,
    'snowLine' : IDL.Float64,
    'snowCoverage' : IDL.Float64,
  });
  const ThermalSettings = IDL.Record({
    'threshold' : IDL.Float64,
    'transferRatio' : IDL.Float64,
    'gravityStrength' : IDL.Float64,
    'creepFactor' : IDL.Float64,
    'incubation' : IDL.Float64,
  });
  const RiverSettings = IDL.Record({
    'channelStr' : IDL.Float64,
    'rainfallAmt' : IDL.Float64,
    'evaporation' : IDL.Float64,
    'flowMultiplier' : IDL.Float64,
    'maxRiverLength' : IDL.Nat,
    'tributaryDensity' : IDL.Float64,
    'flowThreshold' : IDL.Float64,
    'springFreq' : IDL.Float64,
    'lakeDepth' : IDL.Float64,
    'riverWidth' : IDL.Float64,
  });
  const ErosionSettings = IDL.Record({
    'biomeFactors' : BiomeFactors,
    'wind' : WindSettings,
    'hydraulic' : HydraulicSettings,
    'mountain' : MountainSettings,
    'thermal' : ThermalSettings,
    'river' : RiverSettings,
  });
  const CellConfig = IDL.Record({
    'noiseSettings' : NoiseSettings,
    'lightingSettings' : LightingSettings,
    'erosionSettings' : ErosionSettings,
  });
  const GridConfig = IDL.Record({
    'dim' : IDL.Nat,
    'owner' : IDL.Principal,
    'cells' : IDL.Vec(IDL.Vec(CellConfig)),
  });
  const ItemInstanceMastery = IDL.Record({
    'masteryPoints' : IDL.Nat,
    'owner' : IDL.Principal,
    'masteryLevel' : IDL.Nat,
    'itemInstanceId' : IDL.Vec(IDL.Nat8),
    'characterId' : IDL.Vec(IDL.Nat8),
    'objectType' : WeaponObjectType,
  });
  const StatBuffs = IDL.Record({
    'manaBonus' : IDL.Int,
    'agilityBonus' : IDL.Int,
    'strengthBonus' : IDL.Int,
    'healthBonus' : IDL.Int,
  });
  const WorldBreakingPowers = IDL.Record({
    'efficientMana' : IDL.Bool,
    'allySummoning' : IDL.Bool,
    'aoeUltimates' : IDL.Bool,
    'reducedCooldowns' : IDL.Bool,
  });
  const TierLevel = IDL.Variant({
    'epic' : IDL.Null,
    'legendary' : IDL.Null,
    'rare' : IDL.Null,
    'common' : IDL.Null,
  });
  const Resistances = IDL.Record({
    'physicalResistance' : IDL.Float64,
    'poisonResistance' : IDL.Float64,
    'iceResistance' : IDL.Float64,
    'lightningResistance' : IDL.Float64,
    'fireResistance' : IDL.Float64,
  });
  const LootItem = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'statBuffs' : IDL.Opt(StatBuffs),
    'debuffAbilities' : IDL.Opt(IDL.Vec(IDL.Text)),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'worldBreakingPowers' : IDL.Opt(WorldBreakingPowers),
    'tier' : TierLevel,
    'defensePower' : IDL.Int,
    'attackPower' : IDL.Int,
    'specialTraits' : IDL.Vec(IDL.Text),
    'resistances' : IDL.Opt(Resistances),
    'elementalPower' : IDL.Int,
    'isExcellent' : IDL.Bool,
  });
  const StatRanges = IDL.Record({
    'maxDefense' : IDL.Int,
    'maxAttack' : IDL.Int,
    'minAttack' : IDL.Int,
    'maxElemental' : IDL.Int,
    'minDefense' : IDL.Int,
    'minElemental' : IDL.Int,
  });
  const TierDefinition = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'rarityPercentage' : IDL.Float64,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'statRanges' : StatRanges,
    'level' : TierLevel,
    'specialAttributes' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileType = IDL.Variant({
    'FBX' : IDL.Null,
    'GLB' : IDL.Null,
    'OBJ' : IDL.Null,
    'GLTF' : IDL.Null,
  });
  const ArchiveType = IDL.Variant({ 'tar' : IDL.Null, 'zip' : IDL.Null });
  const FileMetadata = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'extractionSource' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'owner' : IDL.Principal,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'fileType' : FileType,
    'uploadTimestamp' : IDL.Int,
    'relativePath' : IDL.Text,
    'archiveType' : IDL.Opt(ArchiveType),
    'isDirectory' : IDL.Bool,
  });
  const Heightmap = IDL.Record({
    'dim' : IDL.Nat,
    'externalBlob' : ExternalBlob,
    'owner' : IDL.Principal,
  });
  const MasterySkill = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'requiredMasteryLevel' : IDL.Nat,
    'objectType' : WeaponObjectType,
  });
  const MasteryTree = IDL.Record({
    'owner' : IDL.Principal,
    'objectType' : WeaponObjectType,
    'skills' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const ObjectType = IDL.Variant({
    'interactiveObject' : IDL.Null,
    'playerCharacter' : IDL.Null,
    'environmentalObject' : IDL.Null,
    'collectible' : IDL.Null,
    'vehicle' : IDL.Null,
    'nonPlayerCharacter' : IDL.Null,
    'weapon' : IDL.Null,
  });
  const GameObject = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'behavior' : Behavior,
    'owner' : IDL.Principal,
    'appearance' : Appearance,
    'animation' : Animation,
    'position' : Position,
    'objectType' : ObjectType,
  });
  const MasteryRollResult = IDL.Record({
    'skillsUnlocked' : IDL.Nat,
    'total' : IDL.Nat,
    'roll1' : IDL.Nat,
    'roll2' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'applyBuffToMob' : IDL.Func([IDL.Vec(IDL.Nat8), StatusEffect], [], []),
    'applyDebuffToMob' : IDL.Func([IDL.Vec(IDL.Nat8), StatusEffect], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllLootItems' : IDL.Func([], [], []),
    'clearMobBuffs' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'clearMobDebuffs' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'createDefaultMobEntity' : IDL.Func(
        [
          IDL.Vec(IDL.Nat8),
          MobType,
          IDL.Text,
          Position,
          Behavior,
          Animation,
          Appearance,
        ],
        [MobEntity],
        [],
      ),
    'deleteFile' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'deleteLootItem' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'deleteMasterySkill' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'deleteMobEntity' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'deleteObjectPrefab' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'deleteTierDefinition' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'getAllCharacterMasteryProgress' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(CharacterMasteryProgress)],
        ['query'],
      ),
    'getAllGridConfigs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat8), GridConfig))],
        ['query'],
      ),
    'getAllItemInstanceMasteries' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(ItemInstanceMastery)],
        ['query'],
      ),
    'getAllLootItems' : IDL.Func([], [IDL.Vec(LootItem)], ['query']),
    'getAllMobEntities' : IDL.Func([], [IDL.Vec(MobEntity)], ['query']),
    'getAllTierDefinitions' : IDL.Func(
        [],
        [IDL.Vec(TierDefinition)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterMasteryProgress' : IDL.Func(
        [IDL.Vec(IDL.Nat8), WeaponObjectType],
        [IDL.Opt(CharacterMasteryProgress)],
        ['query'],
      ),
    'getDirectoryContents' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getFile' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(FileMetadata)],
        ['query'],
      ),
    'getFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getFilesByExtractionSource' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getGridConfig' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(GridConfig)],
        ['query'],
      ),
    'getHeightmap' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(Heightmap)],
        ['query'],
      ),
    'getItemInstanceMastery' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
        [IDL.Opt(ItemInstanceMastery)],
        ['query'],
      ),
    'getLootItem' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(LootItem)],
        ['query'],
      ),
    'getLootItemsByTier' : IDL.Func(
        [TierLevel],
        [IDL.Vec(LootItem)],
        ['query'],
      ),
    'getLootItemsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(LootItem)],
        ['query'],
      ),
    'getLootTableStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'commonCount' : IDL.Nat,
            'rareCount' : IDL.Nat,
            'legendaryCount' : IDL.Nat,
            'excellentCount' : IDL.Nat,
            'epicCount' : IDL.Nat,
            'totalItems' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMasterySkill' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(MasterySkill)],
        ['query'],
      ),
    'getMasterySkillsByObjectType' : IDL.Func(
        [WeaponObjectType],
        [IDL.Vec(MasterySkill)],
        ['query'],
      ),
    'getMasteryTree' : IDL.Func(
        [WeaponObjectType],
        [IDL.Opt(MasteryTree)],
        ['query'],
      ),
    'getMobBuffDebuffState' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [
          IDL.Opt(
            IDL.Record({
              'dangerRating' : IDL.Nat,
              'activeDebuffs' : IDL.Vec(StatusEffect),
              'activeBuffs' : IDL.Vec(StatusEffect),
            })
          ),
        ],
        ['query'],
      ),
    'getMobEntitiesByDangerRating' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MobEntity)],
        ['query'],
      ),
    'getMobEntity' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(MobEntity)],
        ['query'],
      ),
    'getObjectPrefab' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(GameObject)],
        ['query'],
      ),
    'getObjectPrefabs' : IDL.Func([], [IDL.Vec(GameObject)], ['query']),
    'getTierDefinition' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(TierDefinition)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rollMasteryAdvancement' : IDL.Func(
        [IDL.Vec(IDL.Nat8), WeaponObjectType, IDL.Nat],
        [MasteryRollResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCharacterMasteryProgress' : IDL.Func(
        [CharacterMasteryProgress],
        [],
        [],
      ),
    'saveFile' : IDL.Func(
        [
          IDL.Vec(IDL.Nat8),
          ExternalBlob,
          IDL.Text,
          IDL.Nat,
          FileType,
          IDL.Int,
          IDL.Opt(IDL.Vec(IDL.Nat8)),
          IDL.Text,
          IDL.Bool,
          IDL.Opt(ArchiveType),
        ],
        [],
        [],
      ),
    'saveGridConfig' : IDL.Func([IDL.Vec(IDL.Nat8), GridConfig], [], []),
    'saveHeightmap' : IDL.Func(
        [IDL.Vec(IDL.Nat8), ExternalBlob, IDL.Nat],
        [],
        [],
      ),
    'saveItemInstanceMastery' : IDL.Func([ItemInstanceMastery], [], []),
    'saveLootItem' : IDL.Func([IDL.Vec(IDL.Nat8), LootItem], [], []),
    'saveLootItemBatch' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Vec(IDL.Nat8), LootItem))],
        [],
        [],
      ),
    'saveMasterySkill' : IDL.Func([IDL.Vec(IDL.Nat8), MasterySkill], [], []),
    'saveMasteryTree' : IDL.Func(
        [WeaponObjectType, IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    'saveMobEntity' : IDL.Func([IDL.Vec(IDL.Nat8), MobEntity], [], []),
    'saveObjectPrefab' : IDL.Func([IDL.Vec(IDL.Nat8), GameObject], [], []),
    'saveTierDefinition' : IDL.Func(
        [IDL.Vec(IDL.Nat8), TierDefinition],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };