/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Animation {
  'run' : string,
  'hasIdle' : boolean,
  'hasWalk' : boolean,
  'hasAttack' : boolean,
  'idle' : string,
  'walk' : string,
  'emote' : string,
  'hasRun' : boolean,
  'attack' : string,
  'hasEmote' : boolean,
}
export interface Appearance {
  'pattern' : string,
  'color' : Color,
  'outfitColor' : Color,
  'stats' : Stats,
  'skinTone' : string,
  'material' : string,
}
export type ArchiveType = { 'tar' : null } |
  { 'zip' : null };
export interface Behavior {
  'movement' : Movement,
  'inventorySystem' : InventorySystem,
  'interaction' : Interaction,
  'navigation' : Navigation,
  'combatSystem' : CombatSystem,
  'stealthSystem' : StealthSystem,
  'health' : Health,
}
export interface BiomeFactors {
  'biomeType' : string,
  'forestDensity' : number,
  'vegetation' : number,
  'soilQuality' : number,
}
export interface CellConfig {
  'noiseSettings' : NoiseSettings,
  'lightingSettings' : LightingSettings,
  'erosionSettings' : ErosionSettings,
}
export interface CharacterMasteryProgress {
  'masteryPoints' : bigint,
  'owner' : Principal,
  'masteryLevel' : bigint,
  'unlockedSkillIds' : Array<Uint8Array>,
  'characterId' : Uint8Array,
  'objectType' : WeaponObjectType,
}
export interface Color { 'b' : number, 'g' : number, 'r' : number }
export interface CombatSystem {
  'damage' : bigint,
  'armor' : bigint,
  'canAttack' : boolean,
  'weaponType' : string,
  'experience' : bigint,
}
export interface ErosionSettings {
  'biomeFactors' : BiomeFactors,
  'wind' : WindSettings,
  'hydraulic' : HydraulicSettings,
  'mountain' : MountainSettings,
  'thermal' : ThermalSettings,
  'river' : RiverSettings,
}
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : Uint8Array,
  'extractionSource' : [] | [Uint8Array],
  'owner' : Principal,
  'file' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'fileType' : FileType,
  'uploadTimestamp' : bigint,
  'relativePath' : string,
  'archiveType' : [] | [ArchiveType],
  'isDirectory' : boolean,
}
export type FileType = { 'FBX' : null } |
  { 'GLB' : null } |
  { 'OBJ' : null } |
  { 'GLTF' : null };
export interface GameObject {
  'id' : Uint8Array,
  'behavior' : Behavior,
  'owner' : Principal,
  'appearance' : Appearance,
  'animation' : Animation,
  'position' : Position,
  'objectType' : ObjectType,
}
export interface GridConfig {
  'dim' : bigint,
  'owner' : Principal,
  'cells' : Array<Array<CellConfig>>,
}
export interface Health { 'max' : bigint, 'current' : bigint }
export interface Heightmap {
  'dim' : bigint,
  'externalBlob' : ExternalBlob,
  'owner' : Principal,
}
export interface HydraulicSettings {
  'waterVolume' : number,
  'depositionRate' : number,
  'evaporationRate' : number,
  'transferRate' : number,
  'sedimentCap' : number,
  'iterations' : bigint,
  'erosionStr' : number,
  'rainFreq' : number,
  'rainAmount' : number,
  'soilTransfer' : number,
}
export interface Interaction {
  'interactionType' : string,
  'canInteract' : boolean,
  'interactionRange' : number,
}
export interface InventorySystem {
  'currentInventory' : bigint,
  'inventoryCapacity' : bigint,
}
export interface ItemInstanceMastery {
  'masteryPoints' : bigint,
  'owner' : Principal,
  'masteryLevel' : bigint,
  'itemInstanceId' : Uint8Array,
  'characterId' : Uint8Array,
  'objectType' : WeaponObjectType,
}
export interface LightingSettings {
  'sunlight' : number,
  'shadowDepth' : number,
  'directionalIntensity' : number,
  'elevationTransform' : number,
  'ambientLight' : number,
  'intensity' : number,
}
export interface LootItem {
  'id' : Uint8Array,
  'statBuffs' : [] | [StatBuffs],
  'debuffAbilities' : [] | [Array<string>],
  'owner' : Principal,
  'name' : string,
  'worldBreakingPowers' : [] | [WorldBreakingPowers],
  'tier' : TierLevel,
  'defensePower' : bigint,
  'attackPower' : bigint,
  'specialTraits' : Array<string>,
  'resistances' : [] | [Resistances],
  'elementalPower' : bigint,
  'isExcellent' : boolean,
}
export interface MasteryRollResult {
  'skillsUnlocked' : bigint,
  'total' : bigint,
  'roll1' : bigint,
  'roll2' : bigint,
}
export interface MasterySkill {
  'id' : Uint8Array,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'requiredMasteryLevel' : bigint,
  'objectType' : WeaponObjectType,
}
export interface MasteryTree {
  'owner' : Principal,
  'objectType' : WeaponObjectType,
  'skills' : Array<Uint8Array>,
}
export interface MobEntity {
  'id' : Uint8Array,
  'dangerRating' : bigint,
  'behavior' : Behavior,
  'activeDebuffs' : Array<StatusEffect>,
  'activeBuffs' : Array<StatusEffect>,
  'owner' : Principal,
  'appearance' : Appearance,
  'name' : string,
  'animation' : Animation,
  'mobType' : MobType,
  'position' : Position,
  'health' : Health,
}
export type MobType = { 'orc' : null } |
  { 'troll' : null } |
  { 'custom' : string } |
  { 'goblin' : null } |
  { 'wraith' : null } |
  { 'skeleton' : null };
export interface MountainSettings {
  'flatteningStr' : number,
  'threshold' : number,
  'plateauHeight' : number,
  'smoothingStr' : number,
  'snowLine' : number,
  'snowCoverage' : number,
}
export interface Movement {
  'canJump' : boolean,
  'aggroRadius' : number,
  'speed' : number,
  'canFly' : boolean,
}
export interface Navigation {
  'waypoints' : Array<Position>,
  'canNavigate' : boolean,
  'patrolPaths' : Array<Position>,
}
export interface NoiseSettings {
  'roughness' : number,
  'radialWeight' : number,
  'scale' : number,
  'heightRange' : number,
  'noiseSeed' : bigint,
  'intensity' : number,
}
export type ObjectType = { 'interactiveObject' : null } |
  { 'playerCharacter' : null } |
  { 'environmentalObject' : null } |
  { 'collectible' : null } |
  { 'vehicle' : null } |
  { 'nonPlayerCharacter' : null } |
  { 'weapon' : null };
export interface Position { 'x' : number, 'y' : number, 'z' : number }
export interface Resistances {
  'physicalResistance' : number,
  'poisonResistance' : number,
  'iceResistance' : number,
  'lightningResistance' : number,
  'fireResistance' : number,
}
export interface RiverSettings {
  'channelStr' : number,
  'rainfallAmt' : number,
  'evaporation' : number,
  'flowMultiplier' : number,
  'maxRiverLength' : bigint,
  'tributaryDensity' : number,
  'flowThreshold' : number,
  'springFreq' : number,
  'lakeDepth' : number,
  'riverWidth' : number,
}
export interface StatBuffs {
  'manaBonus' : bigint,
  'agilityBonus' : bigint,
  'strengthBonus' : bigint,
  'healthBonus' : bigint,
}
export interface StatRanges {
  'maxDefense' : bigint,
  'maxAttack' : bigint,
  'minAttack' : bigint,
  'maxElemental' : bigint,
  'minDefense' : bigint,
  'minElemental' : bigint,
}
export interface Stats {
  'stamina' : bigint,
  'strength' : bigint,
  'defense' : bigint,
  'agility' : bigint,
  'charisma' : bigint,
  'intelligence' : bigint,
}
export interface StatusEffect {
  'name' : string,
  'effectId' : Uint8Array,
  'isBuff' : boolean,
  'description' : string,
  'durationSeconds' : number,
  'magnitude' : number,
}
export interface StealthSystem { 'isHidden' : boolean }
export interface ThermalSettings {
  'threshold' : number,
  'transferRatio' : number,
  'gravityStrength' : number,
  'creepFactor' : number,
  'incubation' : number,
}
export interface TierDefinition {
  'id' : Uint8Array,
  'rarityPercentage' : number,
  'owner' : Principal,
  'name' : string,
  'statRanges' : StatRanges,
  'level' : TierLevel,
  'specialAttributes' : Array<string>,
}
export type TierLevel = { 'epic' : null } |
  { 'legendary' : null } |
  { 'rare' : null } |
  { 'common' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeaponObjectType = { 'axe' : null } |
  { 'bow' : null } |
  { 'dagger' : null } |
  { 'shield' : null } |
  { 'custom' : string } |
  { 'mace' : null } |
  { 'wand' : null } |
  { 'spear' : null } |
  { 'staff' : null } |
  { 'sword' : null };
export interface WindSettings {
  'direction' : number,
  'iterations' : bigint,
  'erosionRate' : number,
  'sedimentTransfer' : number,
  'windStrength' : number,
}
export interface WorldBreakingPowers {
  'efficientMana' : boolean,
  'allySummoning' : boolean,
  'aoeUltimates' : boolean,
  'reducedCooldowns' : boolean,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'applyBuffToMob' : ActorMethod<[Uint8Array, StatusEffect], undefined>,
  'applyDebuffToMob' : ActorMethod<[Uint8Array, StatusEffect], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllLootItems' : ActorMethod<[], undefined>,
  'clearMobBuffs' : ActorMethod<[Uint8Array], undefined>,
  'clearMobDebuffs' : ActorMethod<[Uint8Array], undefined>,
  'createDefaultMobEntity' : ActorMethod<
    [Uint8Array, MobType, string, Position, Behavior, Animation, Appearance],
    MobEntity
  >,
  'deleteFile' : ActorMethod<[Uint8Array], undefined>,
  'deleteLootItem' : ActorMethod<[Uint8Array], undefined>,
  'deleteMasterySkill' : ActorMethod<[Uint8Array], undefined>,
  'deleteMobEntity' : ActorMethod<[Uint8Array], undefined>,
  'deleteObjectPrefab' : ActorMethod<[Uint8Array], undefined>,
  'deleteTierDefinition' : ActorMethod<[Uint8Array], undefined>,
  'getAllCharacterMasteryProgress' : ActorMethod<
    [Uint8Array],
    Array<CharacterMasteryProgress>
  >,
  'getAllGridConfigs' : ActorMethod<[], Array<[Uint8Array, GridConfig]>>,
  'getAllItemInstanceMasteries' : ActorMethod<
    [Uint8Array],
    Array<ItemInstanceMastery>
  >,
  'getAllLootItems' : ActorMethod<[], Array<LootItem>>,
  'getAllMobEntities' : ActorMethod<[], Array<MobEntity>>,
  'getAllTierDefinitions' : ActorMethod<[], Array<TierDefinition>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacterMasteryProgress' : ActorMethod<
    [Uint8Array, WeaponObjectType],
    [] | [CharacterMasteryProgress]
  >,
  'getDirectoryContents' : ActorMethod<[Uint8Array], Array<FileMetadata>>,
  'getFile' : ActorMethod<[Uint8Array], [] | [FileMetadata]>,
  'getFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getFilesByExtractionSource' : ActorMethod<[Uint8Array], Array<FileMetadata>>,
  'getGridConfig' : ActorMethod<[Uint8Array], [] | [GridConfig]>,
  'getHeightmap' : ActorMethod<[Uint8Array], [] | [Heightmap]>,
  'getItemInstanceMastery' : ActorMethod<
    [Uint8Array, Uint8Array],
    [] | [ItemInstanceMastery]
  >,
  'getLootItem' : ActorMethod<[Uint8Array], [] | [LootItem]>,
  'getLootItemsByTier' : ActorMethod<[TierLevel], Array<LootItem>>,
  'getLootItemsPaginated' : ActorMethod<[bigint, bigint], Array<LootItem>>,
  'getLootTableStats' : ActorMethod<
    [],
    {
      'commonCount' : bigint,
      'rareCount' : bigint,
      'legendaryCount' : bigint,
      'excellentCount' : bigint,
      'epicCount' : bigint,
      'totalItems' : bigint,
    }
  >,
  'getMasterySkill' : ActorMethod<[Uint8Array], [] | [MasterySkill]>,
  'getMasterySkillsByObjectType' : ActorMethod<
    [WeaponObjectType],
    Array<MasterySkill>
  >,
  'getMasteryTree' : ActorMethod<[WeaponObjectType], [] | [MasteryTree]>,
  'getMobBuffDebuffState' : ActorMethod<
    [Uint8Array],
    [] | [
      {
        'dangerRating' : bigint,
        'activeDebuffs' : Array<StatusEffect>,
        'activeBuffs' : Array<StatusEffect>,
      }
    ]
  >,
  'getMobEntitiesByDangerRating' : ActorMethod<[bigint], Array<MobEntity>>,
  'getMobEntity' : ActorMethod<[Uint8Array], [] | [MobEntity]>,
  'getObjectPrefab' : ActorMethod<[Uint8Array], [] | [GameObject]>,
  'getObjectPrefabs' : ActorMethod<[], Array<GameObject>>,
  'getTierDefinition' : ActorMethod<[Uint8Array], [] | [TierDefinition]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rollMasteryAdvancement' : ActorMethod<
    [Uint8Array, WeaponObjectType, bigint],
    MasteryRollResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCharacterMasteryProgress' : ActorMethod<
    [CharacterMasteryProgress],
    undefined
  >,
  'saveFile' : ActorMethod<
    [
      Uint8Array,
      ExternalBlob,
      string,
      bigint,
      FileType,
      bigint,
      [] | [Uint8Array],
      string,
      boolean,
      [] | [ArchiveType],
    ],
    undefined
  >,
  'saveGridConfig' : ActorMethod<[Uint8Array, GridConfig], undefined>,
  'saveHeightmap' : ActorMethod<[Uint8Array, ExternalBlob, bigint], undefined>,
  'saveItemInstanceMastery' : ActorMethod<[ItemInstanceMastery], undefined>,
  'saveLootItem' : ActorMethod<[Uint8Array, LootItem], undefined>,
  'saveLootItemBatch' : ActorMethod<[Array<[Uint8Array, LootItem]>], undefined>,
  'saveMasterySkill' : ActorMethod<[Uint8Array, MasterySkill], undefined>,
  'saveMasteryTree' : ActorMethod<
    [WeaponObjectType, Array<Uint8Array>],
    undefined
  >,
  'saveMobEntity' : ActorMethod<[Uint8Array, MobEntity], undefined>,
  'saveObjectPrefab' : ActorMethod<[Uint8Array, GameObject], undefined>,
  'saveTierDefinition' : ActorMethod<[Uint8Array, TierDefinition], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];